name: 'ZeroTier Constant Identity Action'
description: 'Join ZeroTier-One using predefined identity provided as input.'
inputs:
  network-id:
    description: 'Your Network ID'
    required: true
  identity:
    description: 'Identity secret key'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
  post: 'cleanup.js'
