name: 'ZeroTier Management Action'
description: 'Adjust local ZeroTier-One node and query other network nodes.'
inputs:
  auth_token:
    required: true
    description: >
      Your ZeroTier Central API Access Token: https://my.zerotier.com/account
  api_url:
    required: false
    default: "https://my.zerotier.com/api/v1"
    description: >
      ZeroTier Central API URL
  ip:
    required: false
    default: ''
    description: >
      Change IP addresses of local node (space separated list). Both IPv4 and IPv6 are acceptable.
      Unchanged by default.
  name:
    required: false
    default: ''
    description: >
      Change name of local node.
      Unchanged by default.
  description:
    required: false
    default: ''
    description: >
      Change description of local node.
      Unchanged by default.
  tags:
    required: false
    default: ''
    description: >
      Change tags of local node  (space separated list of "key=value" pairs).
      Unchanged by default.
  capabilities:
    required: false
    default: ''
    description: >
      Change capabilities of local node (space separated list).
      Unchanged by default.
  wait_for:
    required: false
    default: ''
    description: >
      Name of the node that you want to wait for or a list of expressions defining the nodes
      that you want to wait for. See README for details about expressions.
  timeout:
    required: false
    default: ''
    description: >
      Number of minutes to wait for other nodes. On timeout, the action will fail unless you
      add "?" after the time. Wait forever by default.
  ip_version:
    required: false
    default: '4'
    description: >
      A number telling which IP address version should be used, "4" or "6". You can add "?" to
      allow a different version if specified version is not available, e.g. "6?" use IPv6,
      but if not available, it will fall back to IPv4.
outputs:
  ip:
    description: 'The IP address assigned to local node.'
  wait_for_addresses:
    description: 'Address of each node that you waited for (space separated list).'
  timeout:
    description: '"true" or "false" indicating if timeout occurred.'
runs:
  using: 'node16'
  main: 'dist/main.js'
