name: 'ZeroTier Connection Helper'
description: 'Adjust local ZeroTier-One node and query other network nodes allowing simpler connection setup between them.'
inputs:
  auth_token:
    description: "Your ZeroTier Central API Access Token"
    required: true
  api_url:
    description: "ZeroTier Central API URL"
    required: false
    default: "https://my.zerotier.com/api/v1"
  ip:
    description: 'Change IP addresses of local node (space separated list).'
    required: false
    default: ''
  name:
    description: 'Change name of local node.'
    required: false
    default: ''
  description:
    description: 'Change description of local node.'
    required: false
    default: ''
  tags:
    description: 'Change tags of local node  (space separated list of "key=value" pairs).'
    required: false
    default: ''
  capabilities:
    description: 'Change capabilities of local node (space separated list).'
    required: false
    default: ''
  wait_for:
    description: 'List of other network nodes that you want to wait for (list of selectors, see details in the README).'
    required: false
    default: ''
  timeout:
    description: 'Number of seconds to wait for other nodes. On timeout, the action will fail unless you add question mark "?" after the time. By default, wait forever.'
    required: false
    default: ''
  ip_version:
    description: 'One or two numbers telling what IP address version should be returned in the outputs and used to match with "wait_for", "X" - IPvX, "X Y" - IPvX or IPvY, but prefer IPvX, default "4 6". Special value "list" tells to return all addresses as comma separated list.'
    required: false
    default: '4 6'
outputs:
  ip:
    description: 'The IP address assigned to local node.'
  wait_for_addresses:
    description: 'List of space separated list of addresses.'
  timeout:
    description: '"true" or "false" indicating if timeout occurred.'
runs:
  using: 'node16'
  main: 'dist/main.js'
