name: 'ZeroTier Constant Identity Action'
description: 'Join ZeroTier-One using predefined identity provided as input.'
inputs:
  network-id:
    description: 'Your Network ID'
    required: true
  identity:
    description: 'Identity secret key'
    required: true
outputs:
  ip:
    description: 'The IP address assigned to the node'
runs:
  using: 'node16'
  #pre: 'dist/pre.js'
  main: 'dist/main.js'
  post: 'dist/post.js'
