name: Test

on:
  - workflow_dispatch

jobs:
  main:
    strategy:
      matrix:
        include:
          - os: windows-2022
          - os: windows-2019
          - os: ubuntu-22.04
          - os: ubuntu-20.04
          - os: macos-13
          - os: macos-12
          - os: macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Build
        shell: bash
        env:
          INPUT_AUTH_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
        run: |
          npm ci
          npm run check
          npm run build
          npm run unit-tests
