name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - dist/main.js
      - .github/workflows/main.yml
      - action.yml

jobs:

  StartTestServers:
    strategy:
      matrix:
        include:
          - number: '1'
          - number: '2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Start test servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ip: '192.168.194.25${{ matrix.number }} fde0::25${{ matrix.number }}'
          name: 'TestServer${{ matrix.number }}'
      - name: Wait to stop the servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: 'StopTestServers'
          timeout: 60

  Main:
    strategy:
      matrix:
        include:
          - os: windows-2022
            ip: '192.168.194.201'
            ipv6: 'fde0::201'
          - os: windows-2019
            ip: '192.168.194.202'
            ipv6: 'fde0::202'
          - os: ubuntu-22.04
            ip: '192.168.194.203'
            ipv6: 'fde0::203'
          - os: ubuntu-20.04
            ip: '192.168.194.204'
            ipv6: 'fde0::204'
          - os: macos-13
            ip: '192.168.194.205'
            ipv6: 'fde0::205'
          - os: macos-12
            ip: '192.168.194.206'
            ipv6: 'fde0::206'
          - os: macos-11
            ip: '192.168.194.207'
            ipv6: 'fde0::207'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Build
        shell: bash
        env:
          INPUT_AUTH_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
        run: |
          npm ci
          npm run check
          npm run build
          npm run unit-tests
      - name: Wait for the test servers
        id: zerotier
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[name=TestServer1] [name=TestServer2]'
          timeout: 7
      - name: Info
        shell: bash
        run: |
          echo Your address: ${{ steps.zerotier.outputs.ip }}
          echo Servers: ${{ steps.zerotier.outputs.wait_for_addresses }}

  StopTestServers:
    runs-on: ubuntu-latest
    needs: Main
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Indicate to stop test servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          name: 'StopTestServers'
      - name: Sleep
        shell: bash
        run: sleep 300
