name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - dist/main.js
      - .github/workflows/main.yml
      - action.yml

jobs:

  WaitForEndOfPreviousBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Wait for servers from previous build
        id: wait1
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[name=TestServer1] [name=TestServer2] [name=StopTestServers] [name^=tester-]'
          wait_for_unavailable: true
          timeout: 20
      - run: sleep 30
      - name: Wait again just to be sure
        id: wait2
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[name=TestServer1] [name=TestServer2] [name=StopTestServers] [name^=tester-]'
          wait_for_unavailable: true
          timeout: 20

  StartTestServer1:
    needs: WaitForEndOfPreviousBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Start test servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ip: '192.168.194.251 fde0::251'
          name: 'TestServer1'
          description: 'First CI Test Server'
          tags: 'department=engineering'
          capabilities: 'fast 4'
          wait_for: 'StopTestServers'
          timeout: 15

  StartTestServer2:
    needs: WaitForEndOfPreviousBuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Start test servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ip: '192.168.194.252 fde0::252'
          name: 'TestServer2'
          description: 'Second CI Test Server'
          tags: '1000=400 floor=first'
          wait_for: 'StopTestServers'
          timeout: 15

  Main1:
    needs: WaitForEndOfPreviousBuild
    strategy:
      matrix:
        include:
          - os: windows-2022
            ip: '201'
          - os: ubuntu-22.04
            ip: '203'
          - os: macos-13
            ip: '205'
          - os: macos-12
            ip: '206'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Build
        shell: bash
        env:
          INPUT_AUTH_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
        run: |
          npm ci
          npm run check
          npm run build
          npm run unit-tests

      - name: By name (simple)
        id: by_name_simple
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ip: '192.168.194.${{ matrix.ip }} fde0::${{ matrix.ip }}'
          name: tester-${{ matrix.os }}
          wait_for: 'TestServer1'
          ip_version: 6
          timeout: 5
      - if: ${{ steps.by_name_simple.outputs.wait_for_addresses != 'fde0::251' }}
        run: exit 1
      - if: ${{ steps.by_name_simple.outputs.ip != format('fde0::{0}', matrix.ip) }}
        run: exit 1

      - name: By tag and cap
        id: by_tag_cap
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: >
            [tag:1000==200] AND
            [tag:department=200] AND
            [tagEnum:1000=engineering] AND
            [tagEnum:department=engineering] AND
            [capabilities~=broken] AND
            NOT [capabilities~=external] AND
            NOT [capabilities~=3]
            [tagEnum:department=manufacturing] AND
            [tag:1==1] AND
            NOT ( [capabilities~=fast] OR
                  [capabilities~=external] OR
                  [capabilities~=broken] )
          timeout: 5
      - if: ${{ steps.by_tag_cap.outputs.wait_for_addresses != '192.168.194.251 192.168.194.252' }}
        run: exit 1
      - if: ${{ steps.by_tag_cap.outputs.ip != format('192.168.194.{0}', matrix.ip) }}
        run: exit 1

  Main2:
    needs: WaitForEndOfPreviousBuild
    strategy:
      matrix:
        include:
          - os: windows-2019
            ip: '202'
          - os: ubuntu-20.04
            ip: '204'
          - os: macos-11
            ip: '207'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Build
        shell: bash
        env:
          INPUT_AUTH_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
        run: |
          npm ci
          npm run check
          npm run build
          npm run unit-tests

      - name: By names
        id: by_names
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          ip: '192.168.194.${{ matrix.ip }} fde0::${{ matrix.ip }}'
          name: tester-${{ matrix.os }}
          wait_for: '[name=TestServer1] OR [name=TestServer2]'
          ip_version: 6
          timeout: 5
      - if: ${{ steps.by_names.outputs.wait_for_addresses != 'fde0::251' && steps.by_names.outputs.wait_for_addresses != 'fde0::252' }}
        run: exit 1
      - if: ${{ steps.by_names.outputs.ip != format('fde0::{0}', matrix.ip) }}
        run: exit 1

      - name: By description
        id: by_desc
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[description^=Second] [description^=First]'
          timeout: 5
      - if: ${{ steps.by_desc.outputs.wait_for_addresses != '192.168.194.252 192.168.194.251' }}
        run: exit 1
      - if: ${{ steps.by_desc.outputs.ip != format('192.168.194.{0}', matrix.ip) }}
        run: exit 1

      - name: Timeout
        id: timeout
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[description=This node does not exists]'
          timeout: 1?
      - if: ${{ steps.timeout.outputs.timeout == false }}
        run: exit 1
      - if: ${{ steps.timeout.outputs.timeout == true }}
        run: echo OK

  StopTestServers:
    runs-on: ubuntu-latest
    needs: [Main1, Main2]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@master
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - name: Indicate to stop test servers
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          name: 'StopTestServers'
      - name: Sleep
        shell: bash
        run: sleep 60
      - name: Wait for shutdown of test servers
        id: wait3
        uses: ./
        with:
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
          wait_for: '[name=TestServer1] [name=TestServer2]'
          wait_for_unavailable: true
          timeout: 7
