name: Test other - ubuntu
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
      - run: |
          sleep 5
          sudo zerotier-cli info
          sudo zerotier-cli -j listnetworks
          ifconfig
          member_id=$(sudo zerotier-cli info | awk '{ print $3 }')
          curl -s -X POST -H "Authorization: token ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}" -d '{"config":{"ipAssignments":["192.168.194.201"]}}' "https://my.zerotier.com/api/v1/network/${{ secrets.NETWORK_ID }}/member/$member_id"
          while ! [[ $(sudo zerotier-cli get ${{ secrets.NETWORK_ID }} ip4 | grep 192.168.194.201) ]]; do echo "IP address not assigned. Waiting..."; sleep 1; done
          sleep 6000


