name: Test myself
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Test myself
        uses: ./
        with:
          identity: ${{ secrets.IDENTITY }}
          network-id: ${{ secrets.NETWORK_ID }}
      - run: |
          sleep 6000
