name: ubuntu-20.04
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test myself
        uses: ./
        with:
          identity: ${{ secrets.IDENTITY }}
          network-id: ${{ secrets.NETWORK_ID }}
