name: Test myself - ubuntu
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test myself
        uses: ./
        id: self
        with:
          identity: ${{ secrets.IDENTITY }}
          network-id: ${{ secrets.NETWORK_ID }}
      - run: |
          echo Output of the previous action ${{ steps.self.outputs.ip }}
          sleep 6000
