name: ubuntu-20.04
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo mkdir -p /var/lib/zerotier-one
          sudo echo -n "${{ secrets.IDENTITY }}" > /var/lib/zerotier-one/identity.secret
          sudo cat identity.secret | sed 's|\(.*\):.*|\1|' > /var/lib/zerotier-one/identity.public
          sudo groupadd zerotier-one
          sudo useradd zerotier-one
          sudo usermod -a -G zerotier-one zerotier-one
          sudo chwon zerotier-one:zerotier-one /var/lib/zerotier-one/identity.secret
          sudo chwon zerotier-one:zerotier-one /var/lib/zerotier-one/identity.public
          sudo sudo chmod 600 "/var/lib/zerotier-one/identity.secret"
          sudo sudo curl -s https://install.zerotier.com | sudo bash
          sudo sudo zerotier-cli join ${{ secrets.NETWORK_ID }}
          sleep 6000
