name: macos
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare job
        run: |
          echo "ZEROTIER_DIR=/Library/Application Support/ZeroTier/One" >> $GITHUB_ENV
          echo "ZEROTIER_OWNER=root:admin" >> $GITHUB_ENV
      - name: Run
        shell: bash
        run: |
          sudo mkdir -p "$ZEROTIER_DIR"
          echo -n "${{ secrets.IDENTITY }}" > identity.secret
          cat identity.secret | sed 's|\(.*\):.*|\1|' > identity.public
          sudo cp identity.secret "$ZEROTIER_DIR/"
          sudo cp identity.public "$ZEROTIER_DIR/"
          sudo chown $ZEROTIER_OWNER "$ZEROTIER_DIR/identity.secret"
          sudo chown $ZEROTIER_OWNER "$ZEROTIER_DIR/identity.public"
          sudo chmod 600 "$ZEROTIER_DIR/identity.secret"
          sudo curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join ${{ secrets.NETWORK_ID }}
          sleep 6000
