name: ubuntu-20.04
on:
  workflow_dispatch:
jobs:
  action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo mkdir -p /var/lib/zerotier-one
          echo -n "${{ secrets.IDENTITY }}" > identity.secret
          cat identity.secret | sed 's|\(.*\):.*|\1|' > identity.public
          sudo cp identity.secret /var/lib/zerotier-one/
          sudo cp identity.public /var/lib/zerotier-one/
          #sudo groupadd zerotier-one
          sudo useradd zerotier-one
          #sudo usermod -a -G zerotier-one zerotier-one
          sudo chown zerotier-one:zerotier-one /var/lib/zerotier-one/identity.secret
          sudo chown zerotier-one:zerotier-one /var/lib/zerotier-one/identity.public
          sudo chmod 600 "/var/lib/zerotier-one/identity.secret"
          sudo curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join ${{ secrets.NETWORK_ID }}
          sleep 6000
